=== magento/data-migration-tool/etc/class-map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="classmap" type="classmapType" />
    <xs:complexType name="classmapType">
        <xs:sequence>
            <xs:element name="rename" type="renameRulesType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="renameRulesType">
        <xs:all maxOccurs="1">
            <xs:element name="from" type="notEmptyString" maxOccurs="1" minOccurs="1"/>
            <xs:element name="to" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/class-map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<classmap xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/class-map.xsd">
    <rename>
        <from>catalog/product_attribute_backend_sku</from>
        <to>Magento\Catalog\Model\Product\Attribute\Backend\Sku</to>
    </rename>
    <rename>
        <from>customer/customer_attribute_backend_website</from>
        <to>Magento\Customer\Model\Customer\Attribute\Backend\Website</to>
    </rename>
    <rename>
        <from>customer/customer_attribute_source_website</from>
        <to>Magento\Customer\Model\Customer\Attribute\Source\Website</to>
    </rename>
</classmap>
