=== magento/data-migration-tool/etc/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
        <xs:documentation>Migration Tool Configuration</xs:documentation>
    </xs:annotation>

    <xs:element name="config" type="configType"/>

    <xs:complexType name="configType">
        <xs:annotation>
            <xs:documentation>Configuration root node</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element name="steps" type="stepsType" maxOccurs="unbounded" minOccurs="1"/>
            <xs:element name="source" type="sourceType" maxOccurs="1" minOccurs="1"/>
            <xs:element name="destination" type="destinationType" maxOccurs="1" minOccurs="1"/>
            <xs:element name="options" type="optionsType" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stepsType">
        <xs:annotation>
            <xs:documentation>Definition of steps.</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element name="step" type="stepType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="mode" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="stepType">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element name="integrity" type="stageType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="data" type="stageType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="delta" type="stageType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="volume" type="stageType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="stageType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9_\\\\]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sourceType">
        <xs:annotation>
            <xs:documentation>Definition data source.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="database" type="resourceTypeDatabase"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="destinationType">
        <xs:annotation>
            <xs:documentation>Definition of data destination.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="database" type="resourceTypeDatabase"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="resourceTypeDatabase">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="host" type="xs:string" use="required"/>
        <xs:attribute name="user" type="xs:string" use="required"/>
        <xs:attribute name="password" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="resourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="database"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="optionsType">
        <xs:annotation>
            <xs:documentation>Definition of options.</xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="map_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="eav_map_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="log_map_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="settings_map_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="sales_order_map_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="delta_document_groups_file" type="xmlFile" maxOccurs="1"/>
            <xs:element name="bulk_size" type="xs:int" maxOccurs="1"/>
            <xs:element name="resource_adapter_class_name" type="xs:string" maxOccurs="1"/>
            <xs:element name="log_file" type="xs:string" maxOccurs="1"/>
            <xs:element name="progress_bar_format" type="xs:string" maxOccurs="1"/>
            <xs:element name="upgrade_customer_password_hash" type="xs:string" maxOccurs="1"/>
            <xs:element name="crypt_key" type="xs:string" maxOccurs="1"/>
            <xs:element name="edition_migrate" type="xs:string" maxOccurs="1"/>
            <xs:element name="init_statements_source" type="xs:string" maxOccurs="1"/>
            <xs:element name="init_statements_destination" type="xs:string" maxOccurs="1"/>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="xmlFile">
        <xs:restriction base="xs:string">
            <xs:pattern value="[-/A-Za-z0-9\._]+\.(xml|dist)"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/config-with-empty-map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/config.xsd">
    <steps mode="migration"/>
    <source>
        <database host="localhost" name="magento1_integration" user="root"/>
    </source>
    <destination>
        <database host="localhost" name="magento2_integration" user="root"/>
    </destination>
    <options>
        <map_file>tests/integration/testsuite/Migration/_files/empty-map.xml</map_file>
        <eav_map_file>tests/integration/testsuite/Migration/_files/eav-map.xml</eav_map_file>
        <log_map_file>tests/integration/testsuite/Migration/_files/map-log.xml</log_map_file>
        <settings_map_file>tests/integration/testsuite/Migration/_files/settings.xml</settings_map_file>
        <sales_order_map_file>test/integration/testsuite/Migration/_files/map/sales.xml</sales_order_map_file>
        <bulk_size>100</bulk_size>
    </options>
</config>

=== magento/data-migration-tool/tests/unit/testsuite/Migration/_files/test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/config.xsd">
    <steps mode="data">
        <step title="Step1">
            <integrity>Migration\Step\SomeStep\Integrity</integrity>
            <volume>Migration\Step\SomeStep\Volume</volume>
        </step>
        <step title="Step2">
            <integrity>Migration\Step\SomeStep\Integrity</integrity>
            <volume>Migration\Step\SomeStep\Volume</volume>
        </step>
    </steps>
    <steps mode="delta">
        <step title="Step1">
            <delta>Migration\Step\SomeStep\Integrity</delta>
        </step>
    </steps>
    <source>
        <database host="localhost" name="magento1" user="root"/>
    </source>
    <destination>
        <database host="localhost" name="magento2" user="root" password="123123q"/>
    </destination>
    <options>
        <map_file>map-file.xml</map_file>
        <eav_map_file>eav-map-file.xml</eav_map_file>
        <log_map_file>etc/map-log.xml</log_map_file>
        <settings_map_file>etc/settings.xml</settings_map_file>
        <sales_order_map_file>map-sales.xml</sales_order_map_file>
        <bulk_size>100</bulk_size>
        <custom_option>custom_option_value</custom_option>
        <source_prefix />
        <dest_prefix />
    </options>
</config>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/ee.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/config.xsd">
    <steps mode="settings">
        <step title="Settings Step">
            <integrity>Migration\Step\Settings\Integrity</integrity>
            <data>Migration\Step\Settings\Data</data>
        </step>
        <step title="Stores Step">
            <integrity>Migration\Step\Stores\Integrity</integrity>
            <data>Migration\Step\Stores\Data</data>
            <volume>Migration\Step\Stores\Volume</volume>
        </step>
    </steps>
    <steps mode="data">
        <step title="EAV Step">
            <integrity>Migration\Step\Eav\Integrity</integrity>
            <data>Migration\Step\Eav\Data</data>
            <volume>Migration\Step\Eav\Volume</volume>
        </step>
        <step title="Custom Customer Attributes Step">
            <integrity>Migration\Step\CustomCustomerAttributes\Integrity</integrity>
            <data>Migration\Step\CustomCustomerAttributes\Data</data>
            <volume>Migration\Step\CustomCustomerAttributes\Volume</volume>
        </step>
        <step title="Map Step">
            <integrity>Migration\Step\Map\Integrity</integrity>
            <data>Migration\Step\Map\Data</data>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Url Rewrite step">
            <integrity>Migration\Step\UrlRewrite\Version11410to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version11410to2000</data>
            <volume>Migration\Step\UrlRewrite\Version11410to2000</volume>
        </step>
        <step title="Log Step">
            <integrity>Migration\Step\Log\Integrity</integrity>
            <data>Migration\Step\Log\Data</data>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="Ratings Step">
            <integrity>Migration\Step\Ratings\Integrity</integrity>
            <data>Migration\Step\Ratings\Data</data>
            <volume>Migration\Step\Ratings\Volume</volume>
        </step>
        <step title="SalesOrder step">
            <integrity>Migration\Step\SalesOrder\Integrity</integrity>
            <data>Migration\Step\SalesOrder\Data</data>
            <volume>Migration\Step\SalesOrder\Volume</volume>
        </step>
    </steps>
    <steps mode="delta">
        <step title="Custom Customer Attributes Step">
            <delta>Migration\Step\CustomCustomerAttributes\Delta</delta>
            <volume>Migration\Step\CustomCustomerAttributes\Volume</volume>
        </step>
        <step title="Map step">
            <delta>Migration\Step\Map\Delta</delta>
        </step>
        <step title="Log Step">
            <delta>Migration\Step\Log\Delta</delta>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="SalesOrder step">
            <delta>Migration\Step\SalesOrder\Delta</delta>
            <volume>Migration\Step\SalesOrder\Volume</volume>
        </step>
    </steps>
    <source>
        <database host="localhost" name="magento1_integration" user="root"/>
    </source>
    <destination>
        <database host="localhost" name="magento2_integration" user="root"/>
    </destination>
    <options>
        <map_file>tests/integration/testsuite/Migration/_files/map.xml</map_file>
        <eav_map_file>tests/integration/testsuite/Migration/_files/ee.map-eav.xml</eav_map_file>
        <eav_attribute_groups_file>tests/integration/testsuite/Migration/_files/eav-attribute-groups.xml</eav_attribute_groups_file>
        <eav_document_groups_file>tests/integration/testsuite/Migration/_files/ee.eav-document-groups.xml</eav_document_groups_file>
        <log_map_file>tests/integration/testsuite/Migration/_files/map-log.xml</log_map_file>
        <settings_map_file>tests/integration/testsuite/Migration/_files/settings.xml</settings_map_file>
        <sales_order_map_file>tests/integration/testsuite/Migration/_files/map-sales.xml</sales_order_map_file>
        <delta_document_groups_file>tests/integration/testsuite/Migration/_files/deltalog.xml</delta_document_groups_file>
        <class_map>tests/integration/testsuite/Migration/_files/class-map.xml</class_map>
        <bulk_size>100</bulk_size>
        <source_prefix />
        <dest_prefix />
        <auto_resolve_urlrewrite_duplicates>1</auto_resolve_urlrewrite_duplicates>
        <edition_migrate>ee-to-ee</edition_migrate>
        <init_statements_source>SET NAMES utf8;</init_statements_source>
        <init_statements_destination>SET NAMES utf8;</init_statements_destination>
    </options>
</config>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/config.xsd">
    <steps mode="settings">
        <step title="Settings step">
            <integrity>Migration\Step\Settings</integrity>
            <data>Migration\Step\Settings</data>
        </step>
        <step title="Stores step">
            <integrity>Migration\Step\Stores</integrity>
            <data>Migration\Step\Stores</data>
            <volume>Migration\Step\Stores</volume>
        </step>
    </steps>
    <steps mode="data">
        <step title="EAV Step">
            <integrity>Migration\Step\Eav\Integrity</integrity>
            <data>Migration\Step\Eav\Data</data>
            <volume>Migration\Step\Eav\Volume</volume>
        </step>
        <step title="Map step">
            <integrity>Migration\Step\Map\Integrity</integrity>
            <data>Migration\Step\Map\Data</data>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Url Rewrite step">
            <integrity>Migration\Step\UrlRewrite\Version191to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version191to2000</data>
            <volume>Migration\Step\UrlRewrite\Version191to2000</volume>
        </step>
        <step title="Log Step">
            <integrity>Migration\Step\Log\Integrity</integrity>
            <data>Migration\Step\Log\Data</data>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="Ratings step">
            <integrity>Migration\Step\Ratings</integrity>
            <data>Migration\Step\Ratings</data>
            <volume>Migration\Step\Ratings</volume>
        </step>
    </steps>
    <steps mode="delta">
        <step title="Map step">
            <delta>Migration\Step\Map\Delta</delta>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Log Step">
            <delta>Migration\Step\Log</delta>
            <volume>Migration\Step\Log</volume>
        </step>
        <step title="SalesOrder step">
            <delta>Migration\Step\SalesOrder</delta>
            <volume>Migration\Step\SalesOrder</volume>
        </step>
    </steps>
    <source version="1.9.1">
        <database host="localhost" name="magento1_integration" user="root"/>
    </source>
    <destination version="2.0.0.0">
        <database host="localhost" name="magento2_integration" user="root"/>
    </destination>
    <options>
        <map_file>tests/integration/testsuite/Migration/_files/map.xml</map_file>
        <eav_map_file>tests/integration/testsuite/Migration/_files/map-eav.xml</eav_map_file>
        <eav_attribute_groups_file>tests/integration/testsuite/Migration/_files/eav-attribute-groups.xml</eav_attribute_groups_file>
        <eav_document_groups_file>tests/integration/testsuite/Migration/_files/eav-document-groups.xml</eav_document_groups_file>
        <log_map_file>tests/integration/testsuite/Migration/_files/map-log.xml</log_map_file>
        <log_document_groups_file>tests/integration/testsuite/Migration/_files/log-document-groups.xml.dist</log_document_groups_file>
        <settings_map_file>tests/integration/testsuite/Migration/_files/settings.xml</settings_map_file>
        <sales_order_map_file>tests/integration/testsuite/Migration/_files/map-sales.xml</sales_order_map_file>
        <delta_document_groups_file>tests/integration/testsuite/Migration/_files/deltalog.xml</delta_document_groups_file>
        <class_map>tests/integration/testsuite/Migration/_files/class-map.xml</class_map>
        <bulk_size>100</bulk_size>
        <source_prefix />
        <dest_prefix />
        <auto_resolve_urlrewrite_duplicates>1</auto_resolve_urlrewrite_duplicates>
    </options>
</config>
