=== magento/data-migration-tool/etc/groups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="groups" type="groupsType">
        <xs:unique name="uniqueGroup">
            <xs:selector xpath="group"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="groupsType">
        <xs:sequence>
            <xs:element name="group" type="groupType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:sequence>
            <xs:element name="document" type="documentType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="attribute" type="attributeType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="notEmptyString" use="required"/>
    </xs:complexType>

    <xs:complexType name="documentType">
        <xs:simpleContent>
            <xs:extension base="notEmptyString">
                <xs:attribute name="key" type="notEmptyString" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="attributeType">
        <xs:simpleContent>
            <xs:extension base="notEmptyString">
                <xs:attribute name="key" type="notEmptyString" use="optional"/>
                <xs:attribute name="type" type="notEmptyString" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== magento/data-migration-tool/tests/unit/testsuite/Migration/_files/eav-document-groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/groups.xsd">
    <group name="documents">
        <document>eav_attribute_group</document>
        <document>eav_attribute_set</document>
    </group>
    <group name="mapped_documents">
        <document key="attribute_id">catalog_eav_attribute</document>
        <document key="attribute_id">customer_eav_attribute</document>
        <document key="entity_type_id">eav_entity_type</document>
    </group>
    <group name="documents_leftover_values">
        <document>catalog_category_entity_datetime</document>
    </group>
</groups>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/customer-document-groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:noNamespaceSchemaLocation="urn:magento:module:Magento_DataMigrationTool:etc/groups.xsd">
    <group name="source_documents">
        <document key="entity_id">customer_entity</document>
        <document key="value_id">customer_entity_datetime</document>
        <document key="value_id">customer_entity_decimal</document>
        <document key="value_id">customer_entity_int</document>
        <document key="value_id">customer_entity_text</document>
        <document key="value_id">customer_entity_varchar</document>
        <document key="entity_id">customer_address_entity</document>
        <document key="value_id">customer_address_entity_datetime</document>
        <document key="value_id">customer_address_entity_decimal</document>
        <document key="value_id">customer_address_entity_int</document>
        <document key="value_id">customer_address_entity_text</document>
        <document key="value_id">customer_address_entity_varchar</document>
    </group>
    <group name="eav_entities">
        <document>customer</document>
        <document>customer_address</document>
    </group>
    <group name="customer">
        <document key="entity_id">customer_entity</document>
        <document key="value_id">customer_entity_datetime</document>
        <document key="value_id">customer_entity_decimal</document>
        <document key="value_id">customer_entity_int</document>
        <document key="value_id">customer_entity_text</document>
        <document key="value_id">customer_entity_varchar</document>
    </group>
    <group name="customer_address">
        <document key="entity_id">customer_address_entity</document>
        <document key="value_id">customer_address_entity_datetime</document>
        <document key="value_id">customer_address_entity_decimal</document>
        <document key="value_id">customer_address_entity_int</document>
        <document key="value_id">customer_address_entity_text</document>
        <document key="value_id">customer_address_entity_varchar</document>
    </group>
    <group name="source_entity_documents">
        <document>customer_entity</document>
        <document>customer_address_entity</document>
    </group>
</groups>
