=== magento/data-migration-tool/etc/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="map" type="mapType" />

    <xs:complexType name="mapType">
        <xs:all>
            <xs:element name="source" type="sourceRulesType" maxOccurs="1" minOccurs="1"/>
            <xs:element name="destination" type="destinationRulesType" maxOccurs="1" minOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="sourceRulesType">
        <xs:sequence>
            <xs:element name="document_rules" type="sourceDocumentRulesType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="field_rules" type="sourceFieldRulesType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="destinationRulesType">
        <xs:sequence>
            <xs:element name="document_rules" type="destinationDocumentRulesType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="field_rules" type="destinationFieldRulesType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sourceDocumentRulesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="rename" type="renameDocumentType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="ignore" type="ignoreDocumentType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="destinationDocumentRulesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="ignore" type="ignoreDocumentType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ignoreDocumentType">
        <xs:sequence>
            <xs:element name="document" type="notEmptyString" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="renameDocumentType">
        <xs:sequence>
            <xs:element name="document" type="notEmptyString" />
            <xs:element name="to" type="notEmptyString" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sourceFieldRulesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="ignore" type="ignoreFieldType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="move" type="moveFieldType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transform" type="transformFieldType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="destinationFieldRulesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="ignore" type="ignoreFieldType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transform" type="transformFieldType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ignoreFieldType">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="field" type="fieldFormatType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="datatype" type="fieldFormatType" minOccurs="1" maxOccurs="1"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="moveFieldType">
        <xs:sequence>
            <xs:element name="field" type="fieldFormatType"/>
            <xs:element name="to" type="fieldFormatType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="transformFieldType">
        <xs:sequence>
            <xs:element name="field" type="fieldFormatType"/>
            <xs:element name="handler" type="handlerType">
                <xs:unique name="uniqueParamName">
                    <xs:selector xpath="param" />
                    <xs:field xpath="@name" />
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="handlerType">
        <xs:sequence>
            <xs:element name="param" type="handlerParamType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="class" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9a-zA-Z_\\\\]+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="handlerParamType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:simpleType name="fieldFormatType">
        <xs:annotation>
            <xs:documentation>Field format: "document_name.field_name"</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[^.]+\.[^.]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/ee.map-eav.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/map.xsd">
    <source>
        <document_rules>
            <rename>
                <document>enterprise_rma_item_eav_attribute</document>
                <to>magento_rma_item_eav_attribute</to>
            </rename>
            <rename>
                <document>enterprise_rma_item_eav_attribute_website</document>
                <to>magento_rma_item_eav_attribute_website</to>
            </rename>
        </document_rules>
        <field_rules>
            <transform>
                <field>eav_attribute.attribute_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_attribute.backend_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_attribute.backend_table</field>
                <handler class="\Migration\Handler\GetDestinationValue">
                    <param name="setNullIfEmpty" value="true"/>
                </handler>
            </transform>
            <transform>
                <field>eav_attribute.frontend_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_attribute.frontend_input</field>
                <handler class="\Migration\Handler\Convert">
                    <param name="map" value="[datetime:date]"/>
                </handler>
            </transform>
            <transform>
                <field>eav_attribute.is_required</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>eav_attribute.frontend_class</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>eav_attribute.frontend_label</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>eav_attribute.source_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_attribute.default_value</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>eav_attribute.note</field>
                <handler class="\Migration\Handler\GetDestinationValue">
                    <param name="setNullIfEmpty" value="true"/>
                </handler>
            </transform>

            <transform>
                <field>catalog_eav_attribute.frontend_input_renderer</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>catalog_eav_attribute.is_visible</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>catalog_eav_attribute.apply_to</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>

            <transform>
                <field>customer_eav_attribute.input_filter</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>customer_eav_attribute.data_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>

            <transform>
                <field>eav_entity_type.entity_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_entity_type.attribute_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_entity_type.entity_table</field>
                <handler class="\Migration\Handler\GetDestinationValue"/>
            </transform>
            <transform>
                <field>eav_entity_type.increment_model</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>
            <transform>
                <field>eav_entity_type.additional_attribute_table</field>
                <handler class="\Migration\Handler\GetDestinationValue">
                    <param name="setNullIfEmpty" value="true"/>
                </handler>
            </transform>
            <transform>
                <field>eav_entity_type.entity_attribute_collection</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>

            <transform>
                <field>eav_attribute_set.sort_order</field>
                <handler class="\Migration\Handler\SetValue">
                    <param name="value" value="100"/>
                </handler>
            </transform>
            <transform>
                <field>eav_attribute_set.attribute_set_name</field>
                <handler class="\Migration\Handler\AddPrefix">
                    <param name="prefix" value="Migration_"/>
                </handler>
            </transform>

            <transform>
                <field>eav_attribute_group.attribute_group_name</field>
                <handler class="\Migration\Handler\AddPrefix">
                    <param name="prefix" value="Migration_"/>
                </handler>
            </transform>
            <transform>
                <field>eav_attribute_group.default_id</field>
                <handler class="\Migration\Handler\SetValue">
                    <param name="value" value="0"/>
                </handler>
            </transform>

            <transform>
                <field>enterprise_rma_item_eav_attribute.input_filter</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertModel"/>
            </transform>

            <transform>
                <field>catalog_eav_attribute.apply_to</field>
                <handler class="\Migration\Handler\EavAttribute\ConvertConfigurableAttribute"/>
            </transform>

            <ignore>
                <field>catalog_eav_attribute.is_configurable</field>
            </ignore>
        </field_rules>
    </source>
    <destination>
        <field_rules>
            <ignore>
                <field>catalog_eav_attribute.is_required_in_admin_store</field>
            </ignore>
            <ignore>
                <field>eav_attribute_group.attribute_group_code</field>
            </ignore>
            <ignore>
                <field>eav_attribute_group.tab_group_code</field>
            </ignore>

            <transform>
                <field>eav_attribute_group.attribute_group_code</field>
                <handler class="\Migration\Handler\EavAttributeGroup\SetGroupCode" />
            </transform>
            <transform>
                <field>eav_attribute_group.tab_group_code</field>
                <handler class="\Migration\Handler\SetValue">
                    <param name="value" value="basic"/>
                </handler>
            </transform>
        </field_rules>
    </destination>
</map>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/map.xsd">
    <source>
        <document_rules>
            <ignore>
                <document>source_table_ignored</document>
            </ignore>
            <ignore>
                <document>table_ignored</document>
            </ignore>
            <ignore>
                <document>source_table_*</document>
            </ignore>
            <ignore>
                <document>sales_flat_order</document>
            </ignore>
            <rename>
                <document>source_table_renamed</document>
                <to>dest_table_renamed</to>
            </rename>
            <rename>
                <document>table_with_data</document>
                <to>table_without_data</to>
            </rename>
        </document_rules>
        <field_rules>
            <ignore>
                <field>source_table.ignored_field</field>
            </ignore>
            <ignore>
                <field>common_table.source_field_ignored</field>
            </ignore>
            <move>
                <field>common_table.field1</field>
                <to>common_table.field1_moved</to>
            </move>
            <move>
                <field>source_table_renamed.moved_field</field>
                <to>dest_table_renamed.moved_field</to>
            </move>
        </field_rules>
    </source>
    <destination>
        <document_rules>
            <ignore>
                <document>dest_table_ignored</document>
            </ignore>
            <ignore>
                <document>dest_table_*</document>
            </ignore>
            <ignore>
                <document>sales_order</document>
            </ignore>
            <ignore>
                <document>eav_entity_int</document>
            </ignore>
            <ignore>
                <document>eav_attribute</document>
            </ignore>
        </document_rules>
        <field_rules>
            <ignore>
                <field>common_table.dest_field_ignored</field>
            </ignore>
            <transform>
                <field>common_table.common_field</field>
                <handler class="\Migration\Handler\SetValue">
                    <param name="value" value="123" />
                </handler>
            </transform>
        </field_rules>
    </destination>
</map>

=== magento/data-migration-tool/tests/unit/testsuite/Migration/_files/map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/map.xsd">
    <source>
        <document_rules>
            <rename>
                <document>source-document</document>
                <to>dest-document</to>
            </rename>
            <ignore>
                <document>source-document-ignored</document>
            </ignore>
            <ignore>
                <document>source-document-ignored*</document>
            </ignore>
        </document_rules>

        <field_rules>
            <ignore>
                <field>source-document.field1</field>
            </ignore>
            <move>
                <field>source-document.field2</field>
                <to>dest-document.field2</to>
            </move>
            <move>
                <field>source-document-ignored.field3</field>
                <to>dest-document-ignored.field3</to>
            </move>
            <move>
                <field>source-document5.field3</field>
                <to>dest-document-ignored.field3</to>
            </move>
            <move>
                <field>source-document5.field4</field>
                <to>dest-document5.field5</to>
            </move>
            <transform>
                <field>source-document.field-with-handler</field>
                <handler class="\Migration\Handler\SetValue">
                    <param name="default_value" value="10"/>
                </handler>
            </transform>
            <ignore>
                <datatype>dest-document5.field6</datatype>
            </ignore>
        </field_rules>
    </source>
    <destination>
        <document_rules>
            <ignore>
                <document>dest-document-ignored</document>
            </ignore>
            <ignore>
                <document>dest-document-ignored*</document>
            </ignore>
        </document_rules>

        <field_rules>
            <ignore>
                <field>dest-document.field-new</field>
            </ignore>
            <ignore>
                <field>dest-document5.field5</field>
            </ignore>
            <ignore>
                <datatype>dest-document5.field6</datatype>
            </ignore>
        </field_rules>
    </destination>
</map>

=== magento/data-migration-tool/tests/integration/testsuite/Migration/_files/map-sales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../../../etc/map.xsd">
    <source>
        <document_rules>
            <rename>
                <document>sales_flat_order</document>
                <to>sales_order</to>
            </rename>
        </document_rules>
        <field_rules>
            <ignore>
                <field>sales_flat_order.reward_points_balance_refunded</field>
            </ignore>
            <ignore>
                <field>sales_flat_order.reward_salesrule_points</field>
            </ignore>
        </field_rules>
    </source>
    <destination />
</map>
